name: CI/CD Pipeline — Build, Test & Package

on:
  workflow_dispatch:

jobs:
  build-test-package:
    name: Build Project and Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ dpkg-dev ruby-dev
          sudo gem install fpm

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make

      - name: Run unit tests
        run: |
          cd build
          ./test_documents

      - name: Create DEB package
        run: |
          cd build
          mkdir -p deb/usr/local/bin
          cp rk deb/usr/local/bin/
          cd deb
          fpm -s dir -t deb -n rk-app -v 1.0 .

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: rk-app-deb
          path: build/deb/rk-app_1.0_amd64.deb

  release-deb:
    name: Create GitHub Release with DEB
    needs: build-test-package
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: rk-app-deb
          path: dist

      - name: Create GitHub Release and attach DEB
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
          files: dist/rk-app_1.0_amd64.deb
          body: |
            Automatically built .deb package with application and tests.
